Develop
charliepoker/simple_banking_system pull request #1
Opened 2021-09-19 17:22 UTC by charliepoker

2021-09-19 17:32 UTC, ozombo requested changes
Why are the JWT flow images added to this commit?

2021-09-19 17:32 UTC, ozombo commented on app/config/auth.config.js
> +  secret: "bezkoder-secret-key"
Why is your secret key this simple and the same from the tutorial?

2021-09-19 17:32 UTC, ozombo commented on app/controllers/auth.controller.js
> +exports.verifyOtp = (req, res, next) => {
How are you handling an already verified OTP?

2021-09-19 17:32 UTC, ozombo commented on app/controllers/auth.controller.js
> +              data: user,
This returns all user data including the hashed password I am certain, why?

2021-09-19 17:32 UTC, ozombo commented on app/controllers/user.controller.js
> +  res.status(200).send("User Content.");
How about sending the user data instead of this static json?

2021-09-19 17:32 UTC, ozombo commented on app/middleware/verifySignUp.js
> +  User.findOne({
Unify this to find the username, email, and phone number at once. Running three functions that could easily be combined into one is bad performmance.

2021-09-19 17:32 UTC, ozombo commented on app/models/user.model.js
> +    otp: {
How are errors handled in the case of an already existing OTP which isn't unlikely.

2021-09-19 17:32 UTC, ozombo commented on app/routes/user.routes.js
> +  app.get("/api/test/all", controller.allAccess);
Why are the endpoints named test?

2021-09-19 17:32 UTC, ozombo commented on server.js
> +  // initial();
Write a function to run this based on an env config. So if its dev run it but if PROD don't run. Always understand you have to figure out to run this once upon deployment else the roles won't be created.

2021-09-19 17:47 UTC, charliepoker commented on app/config/auth.config.js
> +  secret: "bezkoder-secret-key"
fixed

2021-09-19 17:57 UTC, charliepoker commented on app/controllers/auth.controller.js
> +              data: user,
it returns only user fullname now

2021-09-19 18:18 UTC, ozombo commented on app/config/auth.config.js
> +  secret: "bezkoder-secret-key"
Where is the commit? The pr isn't updated

2021-09-19 18:18 UTC, ozombo commented on app/controllers/auth.controller.js
> +              data: user,
Commit?

2021-09-19 18:20 UTC, ozombo commented on app/controllers/auth.controller.js
> +              data: user,
Also why are you returning only the full name when other vital info would be needed? @charliepoker

2021-09-20 11:57 UTC, charliepoker commented on app/config/auth.config.js
> +  secret: "bezkoder-secret-key"
I have modified the secret key

2021-09-20 11:58 UTC, charliepoker commented on app/controllers/auth.controller.js
> +              data: user,
I have modified the returned data from the user.

2021-09-22 11:36 UTC, charliepoker commented on app/routes/user.routes.js
> +  app.get("/api/test/all", controller.allAccess);
they have been named correctly

2021-09-22 11:38 UTC, charliepoker commented on app/models/user.model.js
> +    otp: {
errors are been handled now

2021-09-22 11:39 UTC, charliepoker commented on app/controllers/auth.controller.js
> +exports.verifyOtp = (req, res, next) => {
it has been handled

2021-09-22 12:02 UTC, ozombo approved these changes

2021-09-22 12:02 UTC, merged